# Generated by Django 3.0.8 on 2020-07-23 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrivalCity',
        ),
        migrations.AddField(
            model_name='flight',
            name='dateOfDeparture',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
