# Generated by Django 3.0.8 on 2020-07-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0003_auto_20200723_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrivalCity',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
